name: Build and Deploy Code


# it run our code in all scenario(push and pull) and on each branch possible 
on: [push, pull_request]


# push or pull any on the specified branch it run our code
# on: 
#   push:
#     branched:
#       - "main"
#       - "anotherbranch"

#   pull_request:
#     branch:
#       - "main"   


jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD:              
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30  
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      # - name: say hi to naman
      #   run: echo "hello naman"
      - name: Install python version 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt  
      - name: test with pytest
        run: |
          pip install pytest
          pytest

   
